### ISSUE TITLE
disabling spring's default shutdown hook 

### ISSUE THREAD

**Issue by miklesw** [SchweizerischeBundesbahnen/springboot-graceful-shutdown#3]
Did you have any issues with spring-boot's default shutdown hook shutting down the context before the GracefulShutdownHook?

We managed to disable it in one application using SpringApplication.setRegisterShutdownHook(), however if spring-cloud is enabled, it tries to register the an additional spring context which registers the hook.

**Comment by miklesw** [comment]
It was fixed in spring-cloud 1.1.0. 

https://github.com/spring-cloud/spring-cloud-commons/commit/96ec2d32ea0467abab26b33776667cb7c37533d3

**Comment by manuelwallrapp** [comment]
If you start your springboot app with 

GracefulshutdownSpringApplication.run(YourSpringbootApp.class, args);

The starter will call setRegisterShutdownHook(false); to avoid registering a shutdownhook. 
Is there still an issue for you?
